### ISSUE TITLE
Making the playground  with Appwrite in a more efficient way

### ISSUE THREAD

**Issue by sparkingdark** [appwrite/playground-for-python#19]
Hello I have an Idea to make this live using appwrite and want to do some front end design as well python just like the playground for JS. If it is possible then tell me.

**Comment by vamsi963601** [comment]
yes sir you can absolutely do that with appwrite. May I ask you if you have any rior exoerience with appwrite?

**Comment by sparkingdark** [comment]
No I don't have any prior experience with appwrite but I can learn it and I see some code examples how to use it.

**Comment by vamsi963601** [comment]
Yeah that is pretty simple to learn too
You have experience with docker??

**Comment by sparkingdark** [comment]
Very little like the concept of docker not use it very much. Do you know kubernetes?

**Comment by eldadfux** [comment]
This issue was already assigned here: https://github.com/appwrite/appwrite/issues/503. Please review other open issues if you wish to help the project.
