### ISSUE TITLE
Adding get_collection

### ISSUE THREAD

**Issue by RitikaAg** [appwrite/playground-for-python#30]
please assign this task to me

**Comment by vedanttttt** [comment]
Can you assign it to me , I can try!

**Comment by Nibba2018** [comment]
@RitikaAg What is this all about?

**Comment by RitikaAg** [comment]
@Nibba2018 I wanted to add the get_collection api sample

**Comment by Nibba2018** [comment]
@RitikaAg If you want to create a PR, then it would be better to add atleast 5 such api samples.

**Comment by RitikaAg** [comment]
@Nibba2018 okay I'll do that ,so I can create a pr without an assigned issue?

**Comment by Nibba2018** [comment]
@eldadfux any thoughts regarding this issue.
